[package]
name = "time-machine-inspector"
version = "1.1.2"
description = "A Tauri App"
default-run = "time-machine-inspector"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["dialog-open", "dialog-save", "shell-open"] }
tauri-plugin-vibrancy = { git = "https://github.com/tauri-apps/tauri-plugin-vibrancy", features = ["tauri-impl"] }
plist = { version = "1.3.1", features = ["serde"] }

[patch."https://github.com/tauri-apps/tauri"]
tauri = { git = "https://github.com/probablykasper/tauri", rev = "4c1be45" }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
